client_id = "1644bd452951b1d9399b50199051e659"
name = "ChatCart"
application_url = "https://example.com"
embedded = true

[access_scopes]
scopes = "write_app_proxy,unauthenticated_read_product_listings,unauthenticated_read_product_tags,unauthenticated_read_content,read_themes"

[app_proxy]
url = "/proxy"
subpath = "chat-cart"
prefix = "apps"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
